# Generated by Django 5.1.1 on 2024-09-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livesubdomains',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
