# Generated by Django 5.1.1 on 2024-09-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programe_name', models.CharField(max_length=255, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('config', models.JSONField()),
                ('scopes', models.JSONField()),
                ('ooscopes', models.JSONField()),
            ],
        ),
    ]
