# Generated by Django 5.1.1 on 2024-09-25 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programms', '0002_rename_programe_name_programm_programm_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programm',
            old_name='programm_name',
            new_name='programe_name',
        ),
    ]
