# Generated by Django 5.1.1 on 2024-09-25 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programms', '0003_rename_programm_name_programm_programe_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programm',
            old_name='programe_name',
            new_name='programm_name',
        ),
    ]
