# Generated by Django 5.1.1 on 2024-10-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HTTPx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programm_name', models.CharField(max_length=255)),
                ('subdomain', models.CharField(max_length=255)),
                ('ips', models.JSONField()),
                ('tech', models.JSONField()),
                ('favicon', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('status_code', models.JSONField()),
                ('headers', models.JSONField()),
                ('url', models.CharField(max_length=255)),
                ('final_url', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
