# Generated by Django 5.1.1 on 2024-09-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subenum', '0002_alter_subdomains_programm_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomains',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
